# Generated by Django 4.0.5 on 2022-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expected_date', models.DateField()),
                ('delv_or_not', models.BooleanField()),
                ('confirmation', models.BooleanField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('u_address', models.TextField()),
                ('email', models.EmailField(max_length=250)),
                ('mob_no', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('avilble', models.FloatField()),
                ('w_address', models.TextField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
