# Generated by Django 4.0.5 on 2022-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_no', models.TextField()),
                ('cvv_num', models.IntegerField()),
                ('exp_mon', models.IntegerField()),
                ('exp_day', models.IntegerField()),
                ('pas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_quality', models.TextField()),
                ('present_quantity', models.IntegerField()),
                ('cost_pl', models.FloatField()),
                ('product_dec', models.TextField()),
            ],
        ),
    ]
