# Generated by Django 4.0.5 on 2022-07-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_paym_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_address_pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
