# Generated by Django 4.0.5 on 2022-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_product_p_address_pincode_product_product_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_no', models.TextField()),
                ('pin', models.IntegerField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('houseno', models.IntegerField()),
                ('lanmark', models.TextField()),
            ],
        ),
    ]
