# Generated by Django 4.0 on 2022-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_order_product_id_order_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='paym',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='water',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
