# Generated by Django 4.0 on 2022-07-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
