# Generated by Django 4.0 on 2022-07-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=2)),
                ('available', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
    ]
