# Generated by Django 4.0 on 2022-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(max_length=20),
        ),
    ]
