# Generated by Django 4.0 on 2022-07-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0013_neworder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.user_details'),
        ),
    ]
