# Generated by Django 4.0 on 2022-07-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0014_alter_neworder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('messages', models.CharField(max_length=1000)),
            ],
        ),
    ]
