# Generated by Django 4.0 on 2022-07-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0015_querry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='neworder',
            name='water',
        ),
        migrations.DeleteModel(
            name='Querry',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewOrder',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
